//
//  Strings.swift
//  XiaoFeiXia
//
//  Created by Jason.Chengzi on 15/12/24.
//  Copyright © 2015年 HVIT. All rights reserved.
//

import Foundation

//MARK: Network
//MARK: 数据处理字段
let NETWORK_HANDLING_ARRAY = "NETWORK_HANDLING_ARRAY"
let NETWORK_HANDLING_DICTIONARY = "NETWORK_HANDLING_DICTIONARY"
let NETWORK_HANDLING_STRING = "NETWORK_HANDLING_STRING"
let NETWORK_HANDLING_NUMBER = "NETWORK_HANDLING_NUMBER"
let NETWORK_HANDLING_BOOLEAN = "NETWORK_HANDLING_BOOLEAN"
/*
    *   国际化对应key值
    *
    *   OP_：可操作的
    *   DP_：仅显示的
    *   AL_：提示框的
    *
*/

//MARK: - 应用启动 - Launch

//MARK: - 用户入口 - Entrance
//MARK: 登陆 - Login
let OP_ENTRANCE_LOGIN: String = "OP_ENTRANCE_LOGIN"  //登陆
let OP_ENTRANCE_LOGINING: String = "OP_ENTRANCE_LOGINING"   //登录中
let OP_ENTRANCE_FORGET_PASSWORD: String = "OP_ENTRANCE_FORGET_PASSWORD"    //找回密码
let AL_ENTRANCE_LOGIN_WRONG_USERNAME_OR_PASSWORD = "AL_ENTRANCE_LOGIN_WRONG_USERNAME_OR_PASSWORD"   //账号或密码错误
let AL_ENTRANCE_LOGIN_FAILED_TO_LOGIN = "AL_ENTRANCE_LOGIN_FAILED_TO_LOGIN"  //登录失败
//MARK: 找回密码 - Forget password
let AL_ENTRANCE_FORGET_PASSWORD_INVALID_CODE = "AL_ENTRANCE_FORGET_PASSWORD_INVALID_CODE"   //验证码错误
let AL_ENTRANCE_FORGET_PASSWORD_CODE_SENT = "AL_ENTRANCE_FORGET_PASSWORD_CODE_SENT"  //验证码已发送
let AL_ENTRANCE_FORGET_PASSWORD_FAILED_TO_REQUEST_CODE = "AL_ENTRANCE_FORGET_PASSWORD_FAILED_TO_REQUEST_CODE" //请求验证码失败
//MARK: - 选项卡 - Tab
let OP_TAB_NEW_ORDER: String = "OP_TAB_NEW_ORDER"   //新订单
let OP_TAB_OTHER_ORDER: String = "OP_TAB_OTHER_ORDER" //已处理订单
let OP_TAB_CHAT: String = "OP_TAB_CHAT" //会话列表
let OP_TAB_ME: String = "OP_TAB_ME"  //我的

//MARK: - 订单管理 - Order
//MARK: 综合 - Common
let OP_ORDER_COMMON_NO_MORE: String = "OP_ORDER_COMMON_NO_MORE"    //没有更多订单
let AL_ORDER_COMMON_NEW_COME: String = "AL_ORDER_COMMON_NEW_COME"   //新订单提醒
let AL_ORDER_COMMON_WRONG_ORDER: String = "AL_ORDER_COMMON_WRONG_ORDER"    //订单过期
let AL_ORDER_COMMON_FAILED_TO_CALL: String = "AL_ORDER_COMMON_FAILED_TO_CALL" //呼叫失败
let AL_ORDER_COMMON_WRONG_ORDER_TYPE: String = "AL_ORDER_COMMON_WRONG_ORDER_TYPE"   //订单状态错误
//MARK: 新订单 - New
let AL_ORDER_NEW_ACCEPT_ORDER: String = "AL_ORDER_NEW_ACCEPT_ORDER"  //是否接单
let AL_ORDER_NEW_ACCEPT: String = "AL_ORDER_NEW_ACCEPT"    //立即接单
//MARK: 已处理 - History
let OP_ORDER_HISTORY_TAB_ALL: String = "OP_ORDER_HISTORY_TAB_ALL"   //全部订单
let OP_ORDER_HISTORY_TAB_NOT_FINISHED: String = "OP_ORDER_HISTORY_TAB_NOT_FINISHED"  //待完成
let OP_ORDER_HISTORY_TAB_UNRATED: String = "OP_ORDER_HISTORY_TAB_UNRATED"   //待评价
let OP_ORDER_HISTORY_TAB_CANCELED: String = "OP_ORDER_HISTORY_TAB_CANCELED"  //取消/售后
let AL_ORDER_HISTORY_FINISH_ORDER: String = "AL_ORDER_HISTORY_FINISH_ORDER"  //是否结束服务
let AL_ORDER_HISTORY_FINISH: String = "AL_ORDER_HISTORY_FINISH"    //结束服务
//MARK: 详细 - Detail
//MARK: 评价 - Rate
let DP_ORDER_RATE_RATE: String = "DP_ORDER_RATE_RATE" //评价订单
let DP_ORDER_RATE_NUMBER: String = "DP_ORDER_RATE_NUMBER"   //评分
let DP_ORDER_RATE_REASON: String = "DP_ORDER_RATE_REASON"   //评语
let AL_ORDER_RATE_RATE_ORDER: String = "AL_ORDER_RATE_RATE_ORDER"   //确认评价订单
let AL_ORDER_RATE_SUCCEEDED_TO_RATE: String = "AL_ORDER_RATE_SUCCEEDED_TO_RATE"    //评价成功
//MARK: 拒绝 - Refuse
let DP_ORDER_REFUSE_REASON: String = "DP_ORDER_REFUSE_REASON" //拒单理由
let AL_ORDER_REFUSE_REFUSE_ORDER: String = "AL_ORDER_REFUSE_REFUSE_ORDER"   //确认拒绝订单
let AL_ORDER_REFUSE_SUCCEEDED_TO_REFUSE: String = "AL_ORDER_REFUSE_SUCCEEDED_TO_REFUSE"    //拒单成功
//MARK: - 聊天 - Chat
//MARK: 会话 - Conversation
let DP_CHAT_UNKNOWN_USER: String = "DP_CHAT_UNKNOWN_USER"   //未知用户
let DP_CHAT_ADMINISTER_USER: String = "DP_CHAT_ADMINISTER_USER"    //系统用户
let AL_CHAT_CONVERSATION_EMPTY: String = "AL_CHAT_CONVERSATION_EMPTY" //清空记录
//MARK: - 个人中心 - User
//MARK: 资料 - Information
let DP_USER_INFORMATION_ME: String = "DP_USER_INFORMATION_ME" //商户信息
let DP_USER_INFORMATION_REGION: String = "DP_USER_INFORMATION_REGION" //地区
let DP_USER_INFORMATION_PROFILE_PHOTO: String = "DP_USER_INFORMATION_PROFILE_PHOTO"   //头像
let DP_USER_INFORMATION_PROFILE_CODE: String = "DP_USER_INFORMATION_PROFILE_CODE"   //服务商编号
let DP_USER_INFORMATION_PROFILE_NAME: String = "DP_USER_INFORMATION_PROFILE_NAME"   //服务商名称
let DP_USER_INFORMATION_CONTACTER_NAME: String = "DP_USER_INFORMATION_CONTACTER_NAME"  //联系人
let DP_USER_INFORMATION_CONTACTER_PHONE: String = "DP_USER_INFORMATION_CONTACTER_PHONE"    //联系人电话
let DP_USER_INFORMATION_CONTACTER_ADDRESS: String = "DP_USER_INFORMATION_CONTACTER_ADDRESS"  //通信地址
let DP_USER_INFORMATION_TYPE: String = "DP_USER_INFORMATION_TYPE"   //机构类型
let DP_USER_INFORMATION_SCOPE: String = "DP_USER_INFORMATION_SCOPE"  //经营范围
let DP_USER_INFORMATION_DETAIL_ADDRESS: String = "DP_USER_INFORMATION_DETAIL_ADDRESS" //详细地址
//MARK: 安全 - Secure
let DP_USER_SECURE_PASSWORD_CHANGING: String = "DP_USER_SECURE_PASSWORD_CHANGING"   //修改密码
let DP_USER_SECURE_ENTER_OLD_PASSWORD: String = "DP_USER_SECURE_ENTER_OLD_PASSWORD"    //请输入旧密码
let DP_USER_SECURE_ENTER_NEW_PASSWORD: String = "DP_USER_SECURE_ENTER_NEW_PASSWORD"    //请输入新密码
let DP_USER_SECURE_ENTER_CONFIRM_PASSWORD: String = "DP_USER_SECURE_ENTER_CONFIRM_PASSWORD"    //请再次输入密码
let DP_USER_SECURE_PASSWORD_WRONG_FORM: String = "DP_USER_SECURE_PASSWORD_WRONG_FORM" //密码长度不正确
let DP_USER_SECURE_SAME_PASSWORD: String = "DP_USER_SECURE_SAME_PASSWORD"   //新密码不能和旧密码一样
let DP_USER_SECURE_INCONSISTENT: String = "DP_USER_SECURE_INCONSISTENT"    //两次密码不一致
let DP_USER_SECURE_NULL_PASSWORD: String = "DP_USER_SECURE_NULL_PASSWORD"   //旧密码不能为空
let DP_USER_SECURE_NULL_NEW_PASSWORD: String = "DP_USER_SECURE_NULL_NEW_PASSWORD"   //新密码不能为空
let DP_USER_SECURE_NULL_CONFIRM_PASSWORD: String = "DP_USER_SECURE_NULL_CONFIRM_PASSWORD"   //确认密码不能为空
let DP_USER_SECURE_PASSWORD: String = "DP_USER_SECURE_PASSWORD"    //原密码
let DP_USER_SECURE_NEW_PASSWORD: String = "DP_USER_SECURE_NEW_PASSWORD"    //新密码
let DP_USER_SECURE_CONFIRM_PASSWORD: String = "DP_USER_SECURE_CONFIRM_PASSWORD"    //再次输入密码
let AL_USER_SECURE_CHANGING_SUCCESS: String = "AL_USER_SECURE_CHANGING_SUCCESS"    //修改成功
let AL_USER_SECURE_RELOGIN: String = "AL_USER_SECURE_RELOGIN" //重新登录
let AL_USER_SECURE_WRONG_PASSWORD: String = "AL_USER_SECURE_WRONG_PASSWORD"  //原密码错误
//MARK: 服务项 - Service
let OP_USER_SERVICE: String = "OP_USER_SERVICE" //服务项目
let DP_USER_SERVICE_NO_SERVICE: String = "DP_USER_SERVICE_NO_SERVICE"  //没有服务项
let DP_USER_SERVICE_TYPE: String = "DP_USER_SERVICE_TYPE"   //服务类型
let DP_USER_SERVICE_PRICE: String = "DP_USER_SERVICE_PRICE"  //价格
let DP_USER_SERVICE_CONTENT: String = "DP_USER_SERVICE_CONTENT"    //内容
let DP_USER_SERVICE_AREA: String = "DP_USER_SERVICE_AREA"   //地区
let DP_USER_SERVICE_APPOINTMENT: String = "DP_USER_SERVICE_APPOINTMENT"    //提前预约
let DP_USER_SERVICE_OPENING: String = "DP_USER_SERVICE_OPENING"    //服务时段
let DP_USER_SERVICE_ENABLED: String = "DP_USER_SERVICE_ENABLED"    //服务开启
//MARK: 账户 - Account
let OP_USER_ACCOUNT: String = "OP_USER_ACCOUNT" //我的账户
let OP_USER_ADD_CARD: String = "OP_USER_ADD_CARD"   //添加银行卡
//MARK: 设置 - Setting
let OP_USER_SETTING: String = "OP_USER_SETTING" //设置
let DP_USER_SETTING_NOTIFICATIONS: String = "DP_USER_SETTING_NOTIFICATIONS"  //通知提醒
let DP_USER_SETTING_DESCRIPTION: String = "DP_USER_SETTING_DESCRIPTION"    //通知描述
let DP_USER_SETTING_SECTION_ALERT: String = "DP_USER_SETTING_SECTION_ALERT"  //新消息通知
let DP_USER_SETTING_REMIND: String = "DP_USER_SETTING_REMIND" //新订单提醒
let DP_USER_SETTING_MESSAGE: String = "DP_USER_SETTING_MESSAGE" //新消息提醒
//MARK: 关于 - About
let OP_USER_ABOUT: String = "OP_USER_ABOUT" //关于
//MARK: 退出登录 - Logout
let OP_USER_LOGOUT: String = "OP_USER_LOGOUT"   //退出登陆
let AL_USER_LOGOUT_TITLE: String = "AL_USER_LOGOUT_TITLE"   //退出登录模态框标题
let AL_USER_LOGOUT_MESSAGE: String = "AL_USER_LOGOUT_MESSAGE"   //退出登录模态框内容
let AL_USER_LOGOUT_CONFIRM: String = "AL_USER_LOGOUT_CONFIRM"   //退出登录模态框确定按钮
let AL_USER_LOGOUT_CANCEL: String = "AL_USER_LOGOUT_CANCEL" //退出登录模态框取消按钮

//MARK: - 系统 - System
let OP_SYSTEM_ENABLED: String = "OP_SYSTEM_ENABLED"  //已开启
let OP_SYSTEM_DISABLED: String = "OP_SYSTEM_DISABLED" //已关闭
let OP_SYSTEM_SUBMIT: String = "OP_SYSTEM_SUBMIT"   //提交
let OP_SYSTEM_INSERT: String = "OP_SYSTEM_INSERT"   //插入
let OP_SYSTEM_ADD: String = "OP_SYSTEM_ADD"  //增加
let OP_SYSTEM_NEW: String = "OP_SYSTEM_NEW"  //新增
let OP_SYSTEM_DELETE: String = "OP_SYSTEM_DELETE"   //删除
let OP_SYSTEM_CHANGE: String = "OP_SYSTEM_CHANGE"   //更换
let OP_SYSTEM_ALTER: String = "OP_SYSTEM_ALTER"    //修改
let OP_SYSTEM_BACK: String = "OP_SYSTEM_BACK" //返回
let OP_SYSTEM_CANCEL: String = "OP_SYSTEM_CANCEL"   //取消
let OP_SYSTEM_SHOW: String = "OP_SYSTEM_SHOW" //查看
let OP_SYSTEM_CAMERA: String = "OP_SYSTEM_CAMERA"   //拍照
let OP_SYSTEM_GALARY: String = "OP_SYSTEM_GALARY"   //图库
let AL_SYSTEM_NO_CAMERA: String = "AL_SYSTEM_NO_CAMERA"    //相机不可用
let AL_SYSTEM_NO_GALARY: String = "AL_SYSTEM_NO_GALARY"    //图库不可用
let AL_SYSTEM_UNKNOWN_ERROR: String = "AL_SYSTEM_UNKNOWN_ERROR"    //未知错误
//MARK: 警告框 - Alert
let AL_SYSTEM_ALERT_TITLE: String = "AL_SYSTEM_ALERT_TITLE"  //标题
let AL_SYSTEM_ALERT_MESSAGE: String = "AL_SYSTEM_ALERT_MESSAGE"    //内容
let AL_SYSTEM_ALERT_CONFIRM: String = "AL_SYSTEM_ALERT_CONFIRM"    //确认
let AL_SYSTEM_ALERT_CANCEL: String = "AL_SYSTEM_ALERT_CANCEL" //取消
let AL_SYSTEM_ALERT_OK: String = "AL_SYSTEM_ALERT_OK" //好的
let AL_SYSTEM_ALERT_YES: String = "AL_SYSTEM_ALERT_YES"    //是
let AL_SYSTEM_ALERT_NO: String = "AL_SYSTEM_ALERT_NO" //否
//MARK: 动作框 - ActionSheet
//MARK: 指示框 - Indicator
let AL_SYSTEM_BUILDING_FUNCTION: String = "AL_SYSTEM_BUILDING_FUNCTION"    //功能尚未开发
let AL_SYSTEM_NEW_ORDER: String = "AL_SYSTEM_NEW_ORDER"    //新订单提醒

//MARK: - 网络-Network
//MARK: 失败 - Failed
let AL_NETWORK_FAILED: String = "AL_NETWORK_FAILED"  //操作失败
let AL_NETWORK_FAILED_TO_LOAD: String = "AL_NETWORK_FAILED_TO_LOAD"  //加载失败
let AL_NETWORK_FAILED_CONNECT_TO_SERVER: String = "AL_NETWORK_FAILED_CONNECT_TO_SERVER"    //连接服务器失败
let AL_NETWORK_NO_DATA: String = "AL_NETWORK_NO_DATA" //没有数据
let AL_NETWORK_BAD_NETWORK: String = "AL_NETWORK_BAD_NETWORK" //网络状态异常
let AL_NETWORK_FAILED_TO_OPERATE: String = "AL_NETWORK_FAILED_TO_OPERATE"    //修改失败
let AL_NETWORK_OTHER_DEVICE_SIGNED_IN: String = "AL_NETWORK_OTHER_DEVICE_SIGNED_IN"  //其他设备登陆
let AL_NETWORK_FAILED_TO_UPLOAD_PHOTO: String = "AL_NETWORK_FAILED_TO_UPLOAD_PHOTO"  //上传头像失败
let AL_NETWORK_OUT_DATE: String = "AL_NETWORK_OUT_DATE"    //用户信息过期
let AL_NETWORK_INVAILED_PARAMETERS: String = "AL_NETWORK_INVAILED_PARAMETERS" //参数错误
//MARK: 成功 - Succeeded
let AL_NETWORK_SUCCEDDED: String = "AL_NETWORK_SUCCEDDED"   //操作成功
let AL_NETWORK_SUCCEDDED_TO_LOAD: String = "AL_NETWORK_SUCCEDDED_TO_LOAD"    //加载成功
let AL_NETWORK_SUCCEEDED_TO_OPERATE: String = "AL_NETWORK_SUCCEEDED_TO_OPERATE"   //修改成功
let AL_NETWORK_SUCCEEDED_TO_UPLOAD_PHOTO: String = "AL_NETWORK_SUCCEEDED_TO_UPLOAD_PHOTO"   //上传头像成功
//MARK: 操作中 - Operating
let AL_NETWORK_OPERATING_LOADING: String = "AL_NETWORK_OPERATING_LOADING"   //加载中

//MARK: - 其他 - Other
//MARK: 单位 - Measurement
let DP_OTHER_MEASUREMENT_SIGN: String = "DP_OTHER_MEASUREMENT_SIGN"  //金钱符号
let DP_OTHER_MEASUREMENT_CNY: String = "DP_OTHER_MEASUREMENT_CNY"   //元